### ISSUE TITLE
Called manually on modals to doc

### ISSUE THREAD

**Issue by MARVIN1994PL** [gmrgo/gmrui#1]
Like a 
`$('#myModal').modal('toggle');`
`$('#myModal').modal('show');`
`$('#myModal').modal('hide');`

or a hint of

`<div id="modaldemo" class="modal-wrap open" role="dialog">`

**Comment by mattsince87** [comment]
Hi Marvin, you don't need to add/edit any JavaScript in order to call your modals. See [here](https://gmrui.com/modals/) in the documentation.

Callback like this:
`<a href="#" class="open-modal" data-target="#modaldemo">Open Modal</a>`
